Updates following review #10
buerokratt/Mock-Classifier pull request #11
Opened 2022-05-04 14:09 UTC by martinkearn

This PR includes some updated to the Classifier design doc, following input from @decodingahmed

2022-05-04 14:31 UTC, decodingahmed requested changes

2022-05-04 14:31 UTC, decodingahmed commented on docs/technical/mock-classifier-technical-architecture.md
> +If a token is detected with unrecognised text (i.e. text that does not exactly map to one of the labels defined in the Ministries section or the word `random`), this will be treated as an error case.
I think the `{{education,social}}` scenario is one that we should support also. It would save us from awkwardly typing }} {{ etc.   These scenarios are already written and tested in the POC.

Same as above, I'm open on this too but just want to suggest it so we leverage what's been done already instead of re-invent the wheel.

2022-05-04 14:31 UTC, decodingahmed commented on docs/technical/mock-classifier-technical-architecture.md
> +"message":["I want to register my child at school"]
Plural `messages` since it is an array.

```suggestion
"messages":["I want to register my child at school"]
```

2022-05-04 14:31 UTC, decodingahmed commented on docs/technical/mock-classifier-technical-architecture.md
> +"message":["Please return the {{social}} minsitry"]
Plural `messages`
```suggestion
"messages":["Please return the {{social}} ministry"]
```

2022-05-04 14:31 UTC, decodingahmed commented on docs/technical/mock-classifier-technical-architecture.md
> +Other parameters may also be required in order for the Classifier to call back to DMR when the processing is completed (call-back uri for example). Please consult the DMR design documentation for det
Can I suggest that we spell "Callback" as a single word term really to stay consistent with industry standards.

```suggestion
Other parameters may also be required in order for the Classifier to callback to DMR when the processing is completed (callback URI for example). Please consult the DMR design documentation for details of these parameters.
```

2022-05-04 14:31 UTC, decodingahmed commented on docs/technical/mock-classifier-technical-architecture.md
> +The appropriate http status codes will be returned for error scenarios.
```suggestion
The appropriate HTTP status codes will be returned for error scenarios.
```

2022-05-04 14:31 UTC, decodingahmed commented on docs/technical/mock-classifier-technical-architecture.md
> +The request body will be json format following this schema (the value can be any of the label outlined in the Ministries section).
```suggestion
#### Callback

The API will then do its work to establish the ministry.

When the work is complete, the Classifier will call the DMR API with a POST request.

The request body will be JSON format following this schema (the value can be any of the labels outlined in the Ministries section).
```

2022-05-04 14:37 UTC, martinkearn commented on docs/technical/mock-classifier-technical-architecture.md
> +| How do I arrange for my COVID-19 booster vaccination         | social          |
Actually no, the ministry which health comes under is https://en.wikipedia.org/wiki/Ministry_of_Social_Affairs_(Estonia)

2022-05-04 14:39 UTC, martinkearn commented on docs/technical/mock-classifier-technical-architecture.md
> +Spaces are not permitted so an input text of `Please return {{ environment}}` would be treated as an error case.
I actually think the opposite; having a single, well documented way to write tokens in messages will make it simpler to use. Flexibility in this case increases complexity and there is no need to have multiple ways to define a token.

2022-05-04 14:42 UTC, martinkearn commented on docs/technical/mock-classifier-technical-architecture.md
> +If a token is detected with unrecognised text (i.e. text that does not exactly map to one of the labels defined in the Ministries section or the word `random`), this will be treated as an error case.
My thoughts are the same as above on the spaces .... simplicity trumps flexibility and having a single, well-documented syntax for tokens will make it easier to use (most requests for developers are likely to come from saved curl, postman etc so will rarely be typed freehand). I appreciate that we already have the code for this in PoC but that should not determine the production approach.

2022-05-04 15:03 UTC, martinkearn commented on docs/technical/mock-classifier-technical-architecture.md
> +Spaces are not permitted so an input text of `Please return {{ environment}}` would be treated as an error case.
Discussed offline with @decodingahmed and have agreed to keep it as it is.

2022-05-04 15:04 UTC, martinkearn commented on docs/technical/mock-classifier-technical-architecture.md
> +If a token is detected with unrecognised text (i.e. text that does not exactly map to one of the labels defined in the Ministries section or the word `random`), this will be treated as an error case.
Discussed offline with @decodingahmed and have agreed to keep it as it is.

2022-05-04 15:05 UTC, merged

2022-05-05 05:33 UTC, decodingahmed commented on docs/technical/mock-classifier-technical-architecture.md
>  The Classifier will be a REST api with just a single endpoint which is `/classifications`.
Addressed in #12

2022-05-05 05:33 UTC, decodingahmed commented on docs/technical/mock-classifier-technical-architecture.md
> +Expects an `message` parameter which is an array of strings. The strings contains the text representing the input text. This will be defined in a JSON request body, for example
Addressed in #12

2022-05-05 05:33 UTC, decodingahmed commented on docs/technical/mock-classifier-technical-architecture.md
> +Accepts only `POST` requests. Other http verbs will result in `404/NotFound` responses.
Addressed in #12