Adding in CentOps integrated library and configuration
buerokratt/Mock-Classifier pull request #55
Opened 2022-07-19 15:14 UTC by guypritchard

- Mockbot now expects to talk to CentOps to get Dmr location.
- This means configuration to allow this to happen - e.g. a Participant for Mockbot needs to be created.
- This will affect integration tests.

2022-07-19 16:06 UTC, yahya130 approved these changes

2022-07-20 09:39 UTC, decodingahmed requested changes

2022-07-20 09:39 UTC, decodingahmed commented on src/MockClassifier.Api/Program.cs
> +            var centOpsSettings = configuration.GetSection("DmrServiceSettings").Get<CentOpsServiceSettings>();
See comment in this PR: https://github.com/buerokratt/Mock-Bot/pull/40/files#r925385206

I think the same thing applies here too.

2022-07-20 09:39 UTC, decodingahmed commented on src/MockClassifier.Api/appsettings.json
> +    }
This doesn't seem to match the model of the settings object.   Is this right or am I missing something?

2022-07-20 10:51 UTC, decodingahmed approved these changes

2022-07-20 10:53 UTC, merged